baseURL = "https://camunda-demo.org/"
languageCode = "en-us"
title = "Adventures with Camunda's API"
theme = "minimal"


[params]
    author = "Niall Deehan"
    description = "A simple tutorial to learn some of what Camunda's Java API can do"
    githubUsername = "#"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "school-book"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift", "java"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/posts/"
    name = "Get Started"
    weight = 2

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:info@camunda.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/camunda/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/camundaBPM/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/niall-deehan-07455a47/"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "https://stackoverflow.com/questions/tagged/camunda"
    name = "stack-overflow"
    weight = 5
